<?php if (!!Mage::getStoreConfig('stamped_app/stamped_app_settings_group/enable_stamped_widget',Mage::app()->getStore())):  ?>
		<div id="stamped-main-widget" class="stamped stamped-main-widget"
		data-product-id="<?php echo $this->getReviewsProductId() ?>"
		data-name="<?php echo $this->getReviewsProductName() ?>"
		data-url="<?php echo $this->getReviewsProductUrl() ?>"
		data-image-url="<?php echo $this->getReviewsProductImageUrl() ?>"
		data-description="<?php echo $this->getReviewsProductDescription() ?>">
			<?php 
				if (!!Mage::getStoreConfig('stamped_app/stamped_app_cache_group/enable_stamped_cache',Mage::app()->getStore())){
					$arrayData = $this->helper('stamped')->getRichSnippetData(); 
					//print_r($arrayData);
		  			echo $arrayData["html_widget"];
				}
			?>
		</div>
<?php endif ?>