<script>
    function myInit(){
         if(!window.location.href.indexOf("onepage") > -1) {
        StampedFn.init({
            apiKey: '<?php echo $this->getApiPublicKey(); ?>',
            storeUrl: '<?php echo $this->getStampedApiStoreUrl(); ?>'
        });
            }
    }
    </script>
<script async onload="myInit()" type="text/javascript" src="https://cdn1.stamped.io/files/widget.min.js"></script>
<link rel="stylesheet" type="text/css" href="//cdn1.stamped.io/files/widget.min.css">