<script type="text/javascript">
    //<![CDATA[
    function accessDashboard() {
        new Ajax.Request('<?php echo Mage::helper('adminhtml')->getUrl('stamped_app/adminhtml_stamped/accessDashboard') ?>', {
            method:     'get',
            parameters: {
                "store" : "<?php echo Mage::app()->getRequest()->getParam('store', 0); ?>"
            },
            onComplete: function(transport){
                var pattern = /(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/;
                if (pattern.test(transport.responseText)) {
                   window.open(transport.responseText,'_blank');
                }
                else {
                    var html = '<ul class="messages"><li class="error-msg"><ul><li>' + transport.responseText + '</li></ul></li></ul>';
                    $('messages').update(html);    
                }
            }
        });
    }
    //]]>
</script>

<?php 
    echo $this->getLayout()->createBlock('adminhtml/widget_button')
            ->setData(array(
            'id'        => 'access_stamped_button',
            'label'     => $this->helper('adminhtml')->__('Access'),
            'onclick'   => 'javascript:accessDashboard(); return false;'
        )) -> _toHtml(); 
?> 