<script type="text/javascript">
    //<![CDATA[
    function clearRichsnippts() {
        new Ajax.Request('<?php echo Mage::helper('adminhtml')->getUrl('stamped_app/adminhtml_stamped/clearStampedCache') ?>', {
            method:     'get',
            parameters: {
                "store" : "<?php echo Mage::app()->getRequest()->getParam('store', 0); ?>"
            },
            onComplete: function(transport){
               if (transport.responseText == 1){
                    var html = '<ul class="messages"><li class="success-msg"><ul><li>' + 'Your Stamped.io cached data has cleared successfully.' + '</li></ul></li></ul>';
                    $('messages').update(html);
                } 
                else {
                    var html = '<ul class="messages"><li class="error-msg"><ul><li>' + transport.responseText + '</li></ul></li></ul>';
                    $('messages').update(html);    
                }
            }
        });
    }
    //]]>
</script>

<?php 
    echo $this->getLayout()->createBlock('adminhtml/widget_button')
            ->setData(array(
            'id'        => 'clear_cache_button',
            'label'     => $this->helper('adminhtml')->__('Clear Cache'),
            'onclick'   => 'javascript:clearRichsnippts(); return false;'
        )) -> _toHtml(); 
?> 